# Generated by Django 5.0.6 on 2024-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_extractor', '0002_processeddata_delete_processedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
