# Generated by Django 5.0.6 on 2024-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_extractor', '0003_alter_processeddata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
